package com.gopal.jarvisqa;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.speech.*;import android.speech.tts.TextToSpeech;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.Executors;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener{
 int cyan=Color.rgb(67,221,255),text=Color.rgb(233,248,255),muted=Color.rgb(126,151,168),panel=Color.rgb(9,20,38); LinearLayout chat;EditText input;TextView status;Spinner agents;TextToSpeech tts;SpeechRecognizer speech;boolean speak=true;android.content.SharedPreferences prefs;String endpoint,model;ArrayList<JSONObject> history=new ArrayList<>();
 String[] names={"Orchestrator","Test Architect","Bug Investigator","Automation Copilot","API Guardian","Personal Chief"};
 String[] systems={"You are JARVIS, Gopal Pawar's calm AI chief of staff for QA and personal planning.","You are a senior QA Test Architect. Produce structured risk-based cases with IDs, steps, data, expected results and priority.","You are a defect investigator. Produce precise reports with reproduction, actual versus expected, severity, evidence and regression scope.","You are Gopal's automation copilot specializing in Java, Selenium, TestNG, Maven, Cucumber and Playwright TypeScript.","You are an API and data QA specialist for REST, Postman, SQL, security, performance and diagnostics.","You are Gopal's practical personal chief of staff for planning, learning, fitness and priorities."};
 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("jarvis",MODE_PRIVATE);endpoint=prefs.getString("endpoint","http://192.168.1.2:11434");model=prefs.getString("model","qwen3:8b");tts=new TextToSpeech(this,this);ui();speech();}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r,boolean edge){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(edge)g.setStroke(1,cyan);return g;} TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;}
 void ui(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(10),dp(14),dp(10));root.setBackgroundColor(Color.rgb(5,9,18));
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView logo=tv("J",25,cyan);logo.setGravity(Gravity.CENTER);logo.setBackground(bg(Color.rgb(8,29,51),14,true));head.addView(logo,new LinearLayout.LayoutParams(dp(44),dp(44)));TextView title=tv("  JARVIS\n  QA COMMAND CENTER",16,text);head.addView(title,new LinearLayout.LayoutParams(0,dp(55),1));status=tv("● READY",11,Color.rgb(79,255,176));head.addView(status);Button gear=new Button(this);gear.setText("⚙");gear.setTextColor(cyan);gear.setBackgroundColor(Color.TRANSPARENT);gear.setOnClickListener(v->settings());head.addView(gear,new LinearLayout.LayoutParams(dp(52),dp(52)));root.addView(head);
  agents=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,names){public View getView(int p,View c,android.view.ViewGroup x){TextView v=(TextView)super.getView(p,c,x);v.setTextColor(text);v.setTextSize(15);v.setPadding(dp(14),0,0,0);return v;}};agents.setAdapter(a);agents.setBackground(bg(panel,14,true));root.addView(agents,new LinearLayout.LayoutParams(-1,dp(54)));
  ScrollView scroll=new ScrollView(this);chat=new LinearLayout(this);chat.setOrientation(LinearLayout.VERTICAL);chat.setPadding(0,dp(10),0,dp(10));scroll.addView(chat);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));message(false,"Good day, Gopal. Choose an agent, speak naturally, or type a command.");
  LinearLayout quick=new LinearLayout(this);for(String q:new String[]{"Test cases","Bug report","Daily plan"}){Button x=new Button(this);x.setText(q);x.setTextSize(11);x.setTextColor(cyan);x.setBackground(bg(Color.rgb(10,34,51),22,true));x.setOnClickListener(v->{input.setText(((Button)v).getText()+" for ");input.requestFocus();});quick.addView(x,new LinearLayout.LayoutParams(0,dp(42),1));}root.addView(quick);
  LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.BOTTOM);Button mic=new Button(this);mic.setText("◉");mic.setTextSize(23);mic.setTextColor(Color.WHITE);mic.setBackground(bg(Color.rgb(18,154,206),40,true));mic.setOnClickListener(v->listen());bar.addView(mic,new LinearLayout.LayoutParams(dp(54),dp(54)));input=new EditText(this);input.setHint("Speak or type a command…");input.setHintTextColor(muted);input.setTextColor(text);input.setTextSize(16);input.setMaxLines(4);input.setImeOptions(EditorInfo.IME_ACTION_SEND);input.setBackground(bg(panel,14,true));input.setPadding(dp(12),dp(8),dp(12),dp(8));input.setOnEditorActionListener((v,id,e)->{if(id==EditorInfo.IME_ACTION_SEND){send();return true;}return false;});bar.addView(input,new LinearLayout.LayoutParams(0,dp(58),1));Button go=new Button(this);go.setText("➤");go.setTextColor(Color.WHITE);go.setBackground(bg(Color.rgb(25,120,212),14,false));go.setOnClickListener(v->send());bar.addView(go,new LinearLayout.LayoutParams(dp(58),dp(58)));root.addView(bar);setContentView(root);}
 void message(boolean user,String s){TextView v=tv((user?"GOPAL\n":"JARVIS\n")+s,14,text);v.setPadding(dp(14),dp(10),dp(14),dp(10));v.setBackground(bg(user?Color.rgb(20,64,91):panel,15,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(user?dp(40):0,dp(5),user?0:dp(26),dp(5));chat.addView(v,p);((ScrollView)chat.getParent()).post(()->((ScrollView)chat.getParent()).fullScroll(View.FOCUS_DOWN));}
 void send(){String q=input.getText().toString().trim();if(q.isEmpty())return;input.setText("");message(true,q);status.setText("● THINKING");Executors.newSingleThreadExecutor().execute(()->ollama(q));}
 void ollama(String q){try{history.add(new JSONObject().put("role","user").put("content",q));JSONArray ms=new JSONArray();ms.put(new JSONObject().put("role","system").put("content",systems[agents.getSelectedItemPosition()]+" Respond naturally for speech unless structured QA output is needed."));for(int i=Math.max(0,history.size()-10);i<history.size();i++)ms.put(history.get(i));JSONObject body=new JSONObject().put("model",model).put("stream",false).put("messages",ms);HttpURLConnection c=(HttpURLConnection)new URL(endpoint.replaceAll("/$","")+"/api/chat").openConnection();c.setConnectTimeout(6000);c.setReadTimeout(120000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}if(c.getResponseCode()!=200)throw new IOException();StringBuilder raw=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()))){String z;while((z=r.readLine())!=null)raw.append(z);}String ans=new JSONObject(raw.toString()).getJSONObject("message").getString("content");history.add(new JSONObject().put("role","assistant").put("content",ans));runOnUiThread(()->{status.setText("● READY");message(false,ans);if(speak)talk(ans);});}catch(Exception e){runOnUiThread(()->{status.setText("● OFFLINE");message(false,"I cannot reach Ollama. Confirm the computer IP in Settings, use the same Wi-Fi, and allow port 11434 through Windows Firewall.");});}}
 void speech(){if(!SpeechRecognizer.isRecognitionAvailable(this))return;speech=SpeechRecognizer.createSpeechRecognizer(this);speech.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){status.setText("● LISTENING");}public void onResults(Bundle b){ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty()){input.setText(x.get(0));send();}}public void onError(int e){status.setText("● READY");}public void onBeginningOfSpeech(){}public void onRmsChanged(float v){}public void onBufferReceived(byte[]b){}public void onEndOfSpeech(){}public void onPartialResults(Bundle b){}public void onEvent(int a,Bundle b){}});}
 void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},7);return;}Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"en-IN");speech.startListening(i);}
 void talk(String s){tts.setSpeechRate(.94f);tts.setPitch(.98f);tts.speak(s.replaceAll("[*#]",""),TextToSpeech.QUEUE_FLUSH,null,"jarvis");}public void onInit(int x){if(x==TextToSpeech.SUCCESS)tts.setLanguage(Locale.forLanguageTag("en-IN"));}
 void settings(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);EditText ep=new EditText(this);ep.setHint("http://PC-IP:11434");ep.setText(endpoint);box.addView(ep);EditText mo=new EditText(this);mo.setHint("Model");mo.setText(model);box.addView(mo);CheckBox sp=new CheckBox(this);sp.setText("Speak replies aloud");sp.setChecked(speak);box.addView(sp);new AlertDialog.Builder(this).setTitle("Local Ollama connection").setMessage("Use your computer's Wi-Fi IPv4 address, not localhost.").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save & test",(d,w)->{endpoint=ep.getText().toString().trim();model=mo.getText().toString().trim();speak=sp.isChecked();prefs.edit().putString("endpoint",endpoint).putString("model",model).apply();input.setText("Say hello and confirm the connection.");send();}).show();}
 protected void onDestroy(){if(speech!=null)speech.destroy();if(tts!=null)tts.shutdown();super.onDestroy();}
}
